name: techchallenge

services:
  api:
    image: jcoaio/techchallenge:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456Tech
      MYSQL_DATABASE: techchallenge
      MYSQL_USER: sis_techchallenge
      MYSQL_PASSWORD: 123456Tech
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
