apiVersion: v1
kind: Service
metadata:
  name: svc-api
  namespace: hackathon
  labels:
    app: hackathon
    component: api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30085
  selector:
    app: hackathon
    component: api
