name: TechChallenge-Fase2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 123456Tech
          MYSQL_DATABASE: techchallenge
          MYSQL_USER: sis_techchallenge
          MYSQL_PASSWORD: 123456Tech
        options: > 
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306


    steps:
    - name: Baixar codigo fonte
      uses: actions/checkout@v4

    - name: Conectar no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Construir usando Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Enviar imagens para o Docker Hub
      run: |
        docker-compose -f docker-compose.yml push
